language: node_js
node_js:
- '4'
script:
- set -e
- npm run test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/printable-characters.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: cU3PMHYejCExgI1rLEoZzV0zJt1+pQN8Wm6Nj+C2VrzdpZ5t85jI1/YDSazaryFFoV6/k44eKUVN3F5NB+NPFlyaGC/ICFDkMwCQtEgSa3mLqqeoF5EDkZ3sxjGFIPT1zSVeh1jYGqP22P2adw7oTLQxa+OQKFJPkKLsY3an8CQdlTHQEnihoASFwJOVvRDZfmamzoE0JdTwsOOppRiJw1d1b9pprKUwCg4aizDYxpKlTX/Lix2FlKvjkdu8IlbAikZR716uqs0dkGeve5b7xPPmNMQMtL3OY2VOSDV5OHJYD8w0qnQdMC0im7deBpZXUKr36qHhC/BDI+TRH8crnkphg1SbHABvgM6zdAXLovDdpBpV2dXHW9FratdQ+lsVd9lGnaENeYAD+nG3LfueJgh2AR3wqbNo/hrxyfE0qfd5mbmYdGfZd/8Li9yXTmFCXhFWAE0KliVNqHgPzoOOEaHT/3ghq43OWPmgcr3QWBW4FyGqjVEIj8cZGGk3ggFvQwyPGIPdIGVyUOay0/5fKH/JgXEhqxYrDglAe/lcnG7R6xX98oVXzIGh3rYXKustyFdsxp5dCkfgdrIeJFhBHtoKyn5HhesqSin1wBF7EvRc438IytSZYelIiUPIdExGLzdKrZeuLnwSKpekQSq9E4QXieGGEM/UgQOnQwQ/jtw=
env:
  global:
  - secure: lvybnWQtRwftK0Q/Dj5VIr+623Np3+bg8RNwSPeEKyQs75jU/Jf3i3GSiXe0KoqvfAIqumyuXCyAY64y0otbl8WNtnK9hbnLZfKkwiedCM/4ABFEdPFCQOr9019tOJUfmOKO5ABWyuoDagkBMF93q+0izs3uqWZcfJ/5okPecHjGCAASklp/jMEThI3K+Gy8+PFYIMYJkEhwaJzZdSCY3mTZzhxJ2CuM43h0FxYc82yW1zsYD1+pYiiTgyKRb7HUq3Vu1V291uyn6N4SUtqulc0zGUgRoUAfQBE8pvVOWYIlngrPLEyxRow4afU1QfFX08peKIDR9dv6N12WDoad+gH4PKJDIPg0coG2VtOhD/F6EttZ2ccz+SWwTE283dNDG06gPmvE36QNQMcZ9y0GqQ4QDpBSi/Fqh4FDs/6MDdy3LJRUCJwmYdXEI9xaBm62hnkgnkDnX1jIXgS04g+zdM9wPFSxFPFBkRENEZbuKbVhFenVX4zBMvoODdHk3C6uEri/IBHFyCsfGB1pnKI5l/quyrF473WQ4Nl+giSmTYvJiHiByOZdfD6Iac9r3t4lO9FeSTj4Ywcaf+F5OntQLNj8VfUczVfuAIXop/aOcxytd5gSXC6jL/S24xiQsZY68V75wA/xmsOGKf6tpMxlzHbFQq5A7HfzVBC6W+nG0FU=
  - secure: dEc52evfV901izCC4je5OHtnA+FvPY0UIH3veI5dZm6+rDnErxHg0JHyPjuGp9qtLy7AOx6ZZ0INGQ79+x8IqWF+9myMgl/L58h37c/PEUU9eYyn7BX2+teoT2+HbHvQabRBse9SB5ODzH5WdpSRZtsE/G141hCf3h+RnXlqNV+/aHa+TmPnBzBiy6CCGRUSoU5ConU2tSdqw9vhi455mhb7DtJAQLxaKOLBCiRxfBK+7HUFjcfSNpqNlnU70j5xpJAb52TnzPc0NMYw7J6viz5utWPhNaN0AGf86r9xlSWCvNrAS9N/ISj2ODlBf0YDbB9KuTQVvAJ+bFEsr+jSqyiK3Pr+e6c/+Immw0DHmgBfL0AIU6uFrqqtuNsTTLxswPDqlDCUa2Z/xk5LlggmZI4S+FJfRe7dY5ttajbeYZNKY6FfI+rJxd35DrVOV3r9PJhz+ED93jFHkF3wfvREeRFdnLMs1CvPd8EdzVtSo/9xhzVszAYS8dK85wuR5zYGS+O2AeXegBg+e1qOqB5zQU93luGMtv2E6qUm5keW4TOIXmXs69uulhK5aHgZ5H40IlxqHbPblIDuhTdOebnhou5EgYIKN88MnteK52YNeRt91IR3UHMnhlqi2LvktKR+8m5x/v1x4HzyaSIil+qUa5StvCk/Wmyo57rBA+Tj564=
