language: node_js
node_js:
- '4'
script:
- set -e
- npm run test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/printable-characters.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: K6MbURjlpywGPPuzvTWHMeJqCV7GxLnQKS8bC7CWCFYud1w5xGkqwgV1AZNRDxMOfys8fxNcC7XaM2WWFNNCfPhQJod8cE4fzdr1JN4wHYme/1fBEUxDcEXFJEvH6Yo/lA8GXcgoBUlE0wBWlMyhOQFdHicFyLzWGISsF46cdw6QBXwtDOqbJS4xoRNDARIB1plCTqE/aEtgmJtMYA357Kz0DKNVN7cM5ql4y9hTFuLWrnDkzdXuYh5sAOtd9H8ds98AlSfszqMWfT6K/enYyTO7z3BVzSIoEB0XPoOuMvZgPlX8fKuNMd47E/yPA8Q0b8MgdTNiEJrya8wXNFsQ1PgIzFqB0IPtWuQQAN7ChvjGhIZgvaBSYxYu/7zzuEhhiPOnnoQR+q3VkRRoEL/uQhu6i8poKPkAwBGR0J6dxv2rfJUMjUr6n0yoR6iJymUrIJxc43ayHNMyYfYP93Ck3GiPAiWB0LqzL1CA4alA6PNKV8XMShCl7QA/aoBIBB2oFtZoGWoUMbf7zp7YH3kbJipgfw41e4NMSiELMM+/djnTwulDg8SlAiVzu+lSO0Ynx+i09TsicrQfQqlFX8odk1nr+jN9t/yqacVJhW2T2AlFkjrbCTyQWfFQqfTK0wqncsqf+TMftWhdQqaB4ktVet74kbY9Wd5k5taw00U8zBE=
env:
  global:
  - secure: lvybnWQtRwftK0Q/Dj5VIr+623Np3+bg8RNwSPeEKyQs75jU/Jf3i3GSiXe0KoqvfAIqumyuXCyAY64y0otbl8WNtnK9hbnLZfKkwiedCM/4ABFEdPFCQOr9019tOJUfmOKO5ABWyuoDagkBMF93q+0izs3uqWZcfJ/5okPecHjGCAASklp/jMEThI3K+Gy8+PFYIMYJkEhwaJzZdSCY3mTZzhxJ2CuM43h0FxYc82yW1zsYD1+pYiiTgyKRb7HUq3Vu1V291uyn6N4SUtqulc0zGUgRoUAfQBE8pvVOWYIlngrPLEyxRow4afU1QfFX08peKIDR9dv6N12WDoad+gH4PKJDIPg0coG2VtOhD/F6EttZ2ccz+SWwTE283dNDG06gPmvE36QNQMcZ9y0GqQ4QDpBSi/Fqh4FDs/6MDdy3LJRUCJwmYdXEI9xaBm62hnkgnkDnX1jIXgS04g+zdM9wPFSxFPFBkRENEZbuKbVhFenVX4zBMvoODdHk3C6uEri/IBHFyCsfGB1pnKI5l/quyrF473WQ4Nl+giSmTYvJiHiByOZdfD6Iac9r3t4lO9FeSTj4Ywcaf+F5OntQLNj8VfUczVfuAIXop/aOcxytd5gSXC6jL/S24xiQsZY68V75wA/xmsOGKf6tpMxlzHbFQq5A7HfzVBC6W+nG0FU=
